language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: c13Nrj/8Mhdx3JhUgICfMDrNpy2ABpapGj0UjbqGJ2QjeNsa5Cy9lJJmx6hh5kAKp2vA/ZR316oycZ8poFsW8p0a4jzc+QnZvxCNZCI4j+XT6F72CUsHB1OykTlYk4zb5tI5De3x8H5oUX8iWM0JWTm74TNEPcWdI4El3IGK7LkCGFqJXTROyS+FDAxkhpEQcoF3Giqwlv8mpxA6f3b1cNZPHRuaqr0r55XhtaFRCW3QGRJ/aC9Tf2nU9VKhcAiWBZbPgqPbrTlJo8jvul17Cy82ERKR0Anq4UBOwDSR8eTSHvkLCUqenkQ1D+EV/uD/PyLi0BuGqaPyPp78rdRgfmRV9lmTRbvs6TNcfaI+SqCUAVhoszUWmLFAecr9QRa2LyoAFEjineyzSMx34a9Wmn0nQKx1nOeqoBXeQGeCLHJWGwWJ/yd4PPbq509Mtu6+B7PPXIDb38sudYvNc+AEy37G2lCiWmODiVNKl+DVZ+34KPsn7cXWP8m0dADOj5sF1iVc6VyZha4NnNhilufBeD7mQXloVjpMQ5qW1Lf2Glm16E+R+krtGCPnf+8sxrmF+Spe9/pPeY2cAEXj/mgAkSLzuYDKpz4pPXm5lma7Wj22gsP6XV9BQKYhdfX6nUUFyCUzzG5BxWXsupPF/xDfQjomVto2driZRDiu4f/Vhck=
